import "bootstrap/dist/css/bootstrap.min.css";
import { Geist, Geist_Mono, Poppins, Anybody } from "next/font/google";
import Footer from "@/components/commonComponents/Footer";

import "@/styles/globals.css";
import "@/styles/nightwing-dropdown.css";
import Head from "next/head";
import Navbar from "@/components/commonComponents/Navbar";
import { useRouter } from "next/router";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const anybody = Anybody({
  variable: "--font-anybody",
  subsets: ["latin"],
});

export default function App({ Component, pageProps }) {
  const router = useRouter();
  // hide Navbar + Footer on admin pages
  const isAdminRoute = router.pathname.startsWith("/admin");
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
      </Head>
      <div
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} ${anybody.variable} nightwing-bg`}
      >
        <Navbar />

        <main>
          <Component {...pageProps} />
        </main>

        <Footer />
      </div>
    </>
  );
}
