import "bootstrap/dist/css/bootstrap.min.css";
import { Geist, Geist_Mono } from "next/font/google";
import Footer from "@/components/commonComponents/Footer";

import "@/styles/globals.css";
import Head from "next/head";
import Navbar from "@/components/commonComponents/Navbar";
import { Router } from "next/router";
import { useRouter } from "next/router";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function App({ Component, pageProps }) {
  const router = useRouter();
   // hide Navbar + Footer on admin pages
  const isAdminRoute = router.pathname.startsWith("/admin");
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
       
      </Head>
       <div className="nightwing-bg">
        {!isAdminRoute && <Navbar />}

        <main>
          <Component {...pageProps} />
        </main>

        {!isAdminRoute && <Footer />}
      </div>
    </>
  );
}
